version: '3.7'
services:
  mysql:
    image: mysql:8.0.25
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=awesome_password
      - MYSQL_DATABASE=your_db_name
      - MYSQL_USER=backend_user
      - MYSQL_PASSWORD=awesome_password
    ports:
      - '3308:3306'
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    container_name: mysql
